[package]
name = "fs-set-times"
version = "0.0.0"
authors = ["Dan Gohman <dev@sunfishcode.online>"]
description = "Set filesystem timestamps"
documentation = "https://docs.rs/fs-set-times"
license = "Apache-2.0 WITH LLVM-exception OR Apache-2.0 OR MIT"
repository = "https://github.com/sunfishcode/fs-set-times"
edition = "2018"
keywords = ["api", "network", "file"]
categories = ["filesystem", "network-programming"]
readme = "README.md"

[target.'cfg(not(windows))'.dependencies]
posish = "0.0.0"

[target.'cfg(windows)'.dependencies]
winapi = { version = "0.3.9", features = ["winerror", "std"] }

[badges]
maintenance = { status = "actively-developed" }
